name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install things
      run: |
        sudo apt install pandoc texlive-base texlive-fonts-recommended
        tlmgr update --all
        tlmgr install fontspec geometry multicol xunicode xltxtra marginnote sectsty ulem hyperref polyglossia

    - name: Build things
      run: |
        pandoc details.yml -o output.pdf --template=template.tex --pdf-engine=xelatex

